### ISSUE TITLE
DB and archive names, what's the reason for them?

### ISSUE THREAD

**Issue by pfrazee** [yoshuawuyts/multidrive#7]
The name params for the DB and the archives is a little confusing to me. Since multidrive is a part of dat-node now, I want to get this clarified.

 - With the DB, why not just pass in a level instance?
 - With the archives, shouldnt lookup be by pubkey?

**Comment by joehand** [comment]
> multidrive is a part of dat-node

Just to clarify, dat-node *supports* multidrive but it's not a dependency. dat-node isn't opinionated on how the drive are managed, named or not.

The main issue was getting dat-node to work with externally managed drives at all (by multidrive or another module like [wesleytodd/datd](https://github.com/wesleytodd/datd)).

**Comment by pfrazee** [comment]
@joehand yeah but it's in the readme as the recommended way to handle multiple archives, so it's *somewhat* part of it

**Comment by yoshuawuyts** [comment]
> With the DB, why not just pass in a level instance?

Yup, agree - we should do that.

---
> With the archives, shouldnt lookup be by pubkey

yeah, guess that makes sense - we should change that

----
> Edit: I lied! There is this one opinion on the externally managed drives 😃

Yeah, I'm not sure how to better approach this. We could perhaps store it as `archive.metadata.location` property in `hyperdrive` ? The biggest problem I've found so far is how to make sure `hyperdrives` are persisted and recreated correctly between restarts.
